### ISSUE TITLE
Code Sniffer errors due to line endings when installing Gulp on Windows10 PC

### ISSUE THREAD

**Issue by donnietheg** [creativedotdesign/tofino#254]
Getting following errors when run tofino/gulp in CMD:

FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     1 | ERROR | [x] End of line character is invalid; expected "\n" but
       |       |     found "\r\n"

Fixed locally by adding in PS2 Block

    <exclude name="Generic.Files.LineEndings"/>
under
<exclude name="Generic.Formatting.DisallowMultipleStatements.SameLine"/>

**Comment by mrchimp** [comment]
I believe this is intended. The linter is set up to only allow unix-style line endings (i.e. `\n`), not windows-style (`\r\n`) as this can cause problems with code on Linux servers.

Which file is causing the error?
