### ISSUE TITLE
AjaxForm - Date/Time doesn't match Wordpress Time Zone

### ISSUE THREAD

**Issue by iwriteplays** [creativedotdesign/tofino#271]
Line 208 of `src/lib/AjaxForm.php` uses Unix time instead of the native Wordpress time zone. This results in the contact form sending an email with a timestamp that looks wrong.

Changing the line to the following fixes this issue:
`            $value = current_time('d-M-Y H:i:s');
`

**Comment by danimalweb** [comment]
Fixed in Merged PR on Dev Branch.

**Comment by danimalweb** [comment]
This is fixed in the v2.0.0 release.
