### ISSUE TITLE
Dist file names wrong in assets.php

### ISSUE THREAD

**Issue by donnietheg** [creativedotdesign/tofino#284]
Now I am getting a warning when I activate Tofino:

Warning: filemtime(): stat failed for C:\Users\User\Local Sites\medrie-macphee-artsite-20\app\public/wp-content/themes/medrie-macphee-artsite/dist/js/main.js in C:\Users\User\Local Sites\medrie-macphee-artsite-20\app\public\wp-content\themes\medrie-macphee-artsite\src\lib\assets.php on line 120

There is the same warning for /js/head.js and css/main.css

The path is right but seems like the names of these files have changed

file name in code ==> file name in dist/js or /css

 main.js ==> now scrips.js

was head.js ===> head-scripts.

main.css === > styles.css

**Comment by danimalweb** [comment]
@donnietheg Do you remember which version of Tofino this is happening in? Thanks.

**Comment by donnietheg** [comment]
Hi Daniel. I don't recall, but I'll look into it tomorrow to see if I 
can trace it back.

**Comment by danimalweb** [comment]
Unable to reproduce this.
